<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Fnx\AdminBundle\Entity\Cidade;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
    
}