<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscalaFunRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaFunRepository extends EntityRepository
{
       public function loadEscalaFun(){
        
        return $this->getEntityManager()
                ->createQuery('SELECT e,f
                               FROM FnxAdminBundle:EscalaFun e
                               JOIN e.funcionario f
                               JOIN f.tipo t
                               WHERE t.id <> ?1
                               AND e.fim > ?2')
                ->setParameters(array(1 => 2,
                                      2 => new \DateTime()))
                ->getArrayResult();
        
       }
       
       public function loadEscalaFunTurno(){
        
        return $this->getEntityManager()
                ->createQuery('SELECT f,t
                               FROM FnxAdminBundle:Funcionario f
                               JOIN f.tipo t
                               WHERE t.id <> ?1')
                ->setParameter(1, 2)
                ->getResult();
       }
}