<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaRepository extends EntityRepository
{
    public function loadEscala($id){
        
        return $this->getEntityManager()
                ->createQuery('SELECT e,f
                               FROM FnxAdminBundle:Escala e
                               JOIN e.funcionarios f
                               WHERE e.atividade = :id')
                ->setParameter("id", $id)
                ->getArrayResult();
    }
    
    public function verificaEscala($id, $dataInicial, $dataFinal){
       
        return $this->getEntityManager()
                ->createQuery('SELECT e FROM FnxAdminBundle:Escala e 
                               JOIN e.funcionarios f
                               JOIN e.atividade a
                               WHERE e.dtInicio <= :final AND e.dtFim >= :inicial
                               AND f.id = :id
                               AND a.arquivado = 0')
                ->setParameters(array("inicial" => $dataInicial,
                                      "final" => $dataFinal,
                                      "id" => $id,
                                ))
                ->getResult();
    }
    
    public function loadEscalaByFuncionario($id){
        
        return $this->getEntityManager()
                ->createQuery('SELECT e,f,a
                               FROM FnxAdminBundle:Escala e
                               JOIN e.funcionarios f
                               JOIN e.atividade a
                               WHERE f.id = :id
                               AND a.arquivado = :param')
                ->setParameters(array("id" => $id,
                                      "param" => false))
                ->getResult();
    }
  
}