<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EscalaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EscalaRepository extends EntityRepository
{
    public function loadEscala($id){
        
        return $this->getEntityManager()
                ->createQuery('SELECT e.id, e.dtInicio, e.dtFim FROM FnxAdminBundle:Escala e WHERE e.atividade = :id')
                ->setParameter("id", $id)
                ->getArrayResult();
    }
    
    public function verificaEscala($id, $dataInicial, $dataFinal){
       
        return $this->getEntityManager()
                ->createQuery('SELECT e FROM FnxAdminBundle:Escala e 
                               JOIN e.funcionarios f
                               WHERE e.dtInicio <= :final AND e.dtFim >= :inicial
                               AND f.id = :id')
                ->setParameters(array("inicial" => $dataInicial,
                                      "final" => $dataFinal,
                                      "id" => $id,
                                ))
                ->getResult();
        
    }
    
}