<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FuncionarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FuncionarioRepository extends EntityRepository
{ 
    public function loadSalario(){
       
            $qb = $this->createQueryBuilder('f')
                  ->select('f')
                  ->where('f.tipo = :param')
                  ->setParameter("param", "fun");

            return $qb->getQuery()->getArrayResult();
                 
       }
}