<?php

namespace Fnx\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends EntityRepository{
    
    function getRolesByLocal($p1 = 0, $p2 = 0){
        return $this->getEntityManager()->createQuery(
                "SELECT r FROM FnxAdminBundle:Role
                 WHERE r.id <> ?1
                 AND r.id <> ?2")
                ->setParameters(array(1 => $p1, 2 => $p2))
                ->getResult();
    }
    
}