<?php

namespace Fnx\PedidoBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PedidoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoRepository extends EntityRepository
{
    
    public function loadPedidos($condicao){
        switch ($condicao):
            case "abertos":
                $where = " where p.dataPagamento is null";
            case "todos":
                $where = '';
            case "historico":
                $where = "  where p.dataPagamento is not null";
            case "atrasados":
                $where = " where p.previsao < CURRENT_DATE() and p.dataPagamento is null";
        endswitch;
        
        return $this->getEntityManager()->createQuery("select p from \Fnx\PedidoBundle\Entity\Pedido p".$where)->getResult();
    }
}