<?php

namespace Fnx\FinanceiroBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MovimentacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovimentacaoRepository extends EntityRepository
{
    public function loadParcela($id){
        
        return $this->getEntityManager()
                ->createQuery('SELECT a,r,p,m,fp
                               FROM FnxAdminBundle:Atividade a
                               JOIN a.registro r
                               JOIN r.parcelas p
                               JOIN p.movimentacao m
                               JOIN m.formaPagamento fp
                               WHERE a.id = :id')
                ->setParameter("id", $id)
                ->getArrayResult();
    }
}